import type { AICompletionRequest, AICompletionResult, AIProvider } from "./types";
import type { StructuredRecommendation } from "@/lib/schemas/recommendation";
import { NO_SOURCE_MESSAGE } from "@/lib/schemas/recommendation";

interface MockContext {
  triggerText?: string;
  playbook?: {
    title: string;
    clarifyingQuestions: string[];
    likelyCauses: { cause: string; likelihood: string; verificationStep: string }[];
    safeActions: string[];
    escalationCriteria: string[];
  } | null;
  sources?: { documentId: string | null; title: string; section: string | null; relevance: string | null }[];
  eventType?: string;
  issueSummary?: string;
}

/**
 * Deterministic offline provider so the full product flow works without external credentials.
 * Builds a structured recommendation from the matched playbook template and retrieved sources.
 */
export class MockAIProvider implements AIProvider {
  readonly name = "mock";

  async complete(req: AICompletionRequest): Promise<AICompletionResult> {
    let ctx: MockContext = {};
    const marker = req.user.indexOf("\n<mock-context>");
    if (marker !== -1) {
      try {
        ctx = JSON.parse(req.user.slice(marker + "\n<mock-context>".length).replace("</mock-context>", ""));
      } catch { /* fall through to generic */ }
    }
    if (req.system.includes("POST_CALL_MODE")) {
      return this.wrap(JSON.stringify(this.postCall(ctx)));
    }
    return this.wrap(JSON.stringify(this.recommendation(ctx)));
  }

  private recommendation(ctx: MockContext): StructuredRecommendation {
    const pb = ctx.playbook;
    const sources = ctx.sources ?? [];
    const hasSources = sources.length > 0;
    const causes = (pb?.likelyCauses ?? []).slice(0, 3).map((c) => ({
      cause: c.cause,
      likelihood: (["high", "medium", "low"].includes(c.likelihood) ? c.likelihood : "medium") as "high" | "medium" | "low",
      reasoningSummary: "Common pattern for this symptom based on the matched troubleshooting playbook. Not yet confirmed for this customer.",
      verificationStep: c.verificationStep,
    }));
    return {
      eventType: (ctx.eventType as StructuredRecommendation["eventType"]) ?? "troubleshooting_issue",
      issueSummary: ctx.issueSummary ?? ctx.triggerText?.slice(0, 200) ?? "Customer described a technical issue.",
      suggestedResponse: pb
        ? "That's a known pattern with " + pb.title.toLowerCase() + ". Before changing anything, let me verify the current configuration on our side. I'll walk through the most likely causes and confirm which one applies here."
        : "Let me make sure I understand the setup correctly before recommending a change. I'll verify the current configuration first so we fix the actual cause rather than a symptom.",
      clarifyingQuestions: (pb?.clarifyingQuestions ?? [
        "When did this behavior start, and did anything change around that time?",
        "Is this affecting all records or a specific subset?",
      ]).slice(0, 3),
      possibleCauses: causes.length > 0 ? causes : [{
        cause: "Configuration mismatch between the connected systems",
        likelihood: "medium",
        reasoningSummary: "Insufficient information to narrow further; verification needed.",
        verificationStep: "Review the integration settings and recent change history (read-only).",
      }],
      recommendedActions: [
        { action: "Run the read-only verification steps above and confirm which cause applies", riskLevel: "low", requiresApproval: false },
        ...(pb?.safeActions ?? []).slice(0, 2).map((a) => ({ action: a, riskLevel: "low" as const, requiresApproval: false })),
      ],
      missingInformation: causes.length === 0 ? ["Platform and integration details for this customer"] : [],
      warnings: hasSources ? [] : [NO_SOURCE_MESSAGE],
      shouldEscalate: false,
      escalationReason: null,
      confidence: hasSources ? 0.74 : 0.55,
      sources,
    };
  }

  private postCall(ctx: MockContext): Record<string, unknown> {
    const summary = ctx.issueSummary ?? "Technical call covering an active troubleshooting topic.";
    return {
      executiveSummary: summary,
      technicalSummary: "Discussion focused on: " + summary + " Verification steps were identified during the call; see troubleshooting section.",
      customerQuestions: [], issuesDiscussed: [summary], confirmedFacts: [],
      assumptions: ["Generated by the offline engine; review before sharing."],
      likelyCauses: (ctx.playbook?.likelyCauses ?? []).map((c) => c.cause),
      confirmedRootCauses: [], troubleshootingCompleted: [], resolvedIssues: [], unresolvedIssues: [summary],
      decisionsMade: [], customerCommitments: [], internalCommitments: [],
      followUpItems: ["Confirm verification results with the customer"],
      recommendedEscalation: null,
      crmNote: "Call summary: " + summary + "\nNext step: complete verification and confirm root cause.",
      internalTechnicalNote: "Issue: " + summary + "\nStatus: verification in progress.",
      customerEmail: "Hi,\n\nThanks for the time today. Recapping what we covered: " + summary + "\n\nWe are verifying the configuration on our side and will follow up with confirmed findings and next steps.\n\nBest,\n",
      escalationSummary: "Issue: " + summary + "\nEscalation not currently recommended; verification pending.",
      supportTicket: "Summary: " + summary + "\nSteps taken: verification steps identified during live call.",
      engineeringTicket: "Summary: " + summary + "\nRepro/context: see call transcript.",
      knowledgeBaseUpdate: null,
    };
  }

  private wrap(text: string): AICompletionResult {
    return { text, inputTokens: 0, outputTokens: 0, model: "mock-deterministic-v1", provider: this.name };
  }
}
